openapi: 3.0.2
info:
  title: Lee's API
  version: '1.0'
servers:
  - url: http://127.0.0.1:8080/v1
paths:
  /health:
    get:
      responses:
        '200':
          description: OK
  /customer/{id}:
    get:
      description: Get details of a customer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/customer'
  /customer:
    post:
      description: ''
      parameters: []
      responses:
        '200':
          description: OK
      summary: Create a new customer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/customer'
              description: New customer details
components:
  schemas:
    customer:
      type: object
      properties:
        name:
          type: string
        creditLimit:
          type: number
          description: Maximum credit allowed in NZD
      description: Customer
      required:
        - name
        - creditLimit
 


